# =============================================================================
# GROW GYMIX - DOCKER COMPOSE CONFIGURATION
# =============================================================================
# Docker Compose setup for local development and remote agent environments

version: '3.8'

services:
  # =============================================================================
  # MAIN APPLICATION
  # =============================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "3000:3000"  # Convex dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_ENV=development
      - VITE_APP_URL=http://localhost:5173
      - VITE_ENABLE_DEBUG=true
      - VITE_SHOW_DEV_TOOLS=true
    env_file:
      - .env.development
      - .env.local
    depends_on:
      - database
    networks:
      - grow-gymix-network

  # =============================================================================
  # DATABASE (PostgreSQL for production-like environment)
  # =============================================================================
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: grow_gymix
      POSTGRES_USER: grow_user
      POSTGRES_PASSWORD: grow_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - grow-gymix-network

  # =============================================================================
  # REDIS (for caching and sessions)
  # =============================================================================
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - grow-gymix-network

  # =============================================================================
  # REMOTE AGENT ENVIRONMENT
  # =============================================================================
  remote-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - NODE_ENV=development
      - AUGMENT_DEV_MODE=true
      - AUGMENT_LOG_LEVEL=verbose
      - GITHUB_REPO=grow-grow-coder/grow-gymix
    volumes:
      - .:/workspace
      - /workspace/node_modules
    networks:
      - grow-gymix-network
    depends_on:
      - app
      - database

  # =============================================================================
  # DEVELOPMENT TOOLS
  # =============================================================================
  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - grow-gymix-network

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  grow-gymix-network:
    driver: bridge
